# Generated by Django 5.2.5 on 2025-09-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogreaction_commentreaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogreaction',
            old_name='is_like',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='commentreaction',
            old_name='is_like',
            new_name='like',
        ),
    ]
