# Generated by Django 5.2.5 on 2025-09-01 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_is_like_blogreaction_like_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentreaction',
            name='user',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_likes', to='blog.like'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='blog.like'),
        ),
        migrations.DeleteModel(
            name='BlogReaction',
        ),
        migrations.DeleteModel(
            name='CommentReaction',
        ),
    ]
