# Generated by Django 5.2.5 on 2025-09-01 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislike',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dislike', to='blog.comment'),
        ),
    ]
